CREATE TABLE PLAYERS 
	( Gamertag		VARCHAR(15)		NOT NULL,
	  XUID			CHAR(16)		NOT NULL,
	 PRIMARY KEY (XUID));
CREATE TABLE FRIENDS_OF 
	( PXUID			CHAR(16)		NOT NULL,
	  FXUID			CHAR(16)		NOT NULL,
	 PRIMARY KEY (PXUID, FXUID),
	 FOREIGN KEY (PXUID) REFERENCES PLAYERS(XUID) );
CREATE TABLE GAMES
	( GameTitle		VARCHAR(60)		NOT NULL,
	  GameID		CHAR(10)		NOT NULL,
	 PRIMARY KEY (GameID));
CREATE TABLE GAMES_PLAYED
	( PlayerXUID		CHAR(16)		NOT NULL,
	  GID	 		CHAR(10)		NOT NULL,
	  TimePlayed		INT,
	  GameProgress		INT,
	 PRIMARY KEY (PlayerXUID, GID),
	 FOREIGN KEY (PlayerXUID) REFERENCES PLAYERS(XUID), 
	 FOREIGN KEY (GID) REFERENCES GAMES(GameID) );
CREATE TABLE PLAYLISTS 
	( PName			VARCHAR(72)		NOT NULL,
	  PTag			CHAR(36)		NOT NULL,
	  PID			CHAR(2)			NOT NULL,
	 PRIMARY KEY (PID));
CREATE TABLE SEASONS 
	( SName			VARCHAR(20)		NOT NULL,
	  STag			CHAR(36)		NOT NULL,
	  SID			CHAR(1)			NOT NULL,
	 PRIMARY KEY (SID));
CREATE TABLE RANKS 
	( RankID		CHAR(1)			NOT NULL,
	  RankName		VARCHAR(8)		NOT NULL,
	 PRIMARY KEY (RankID));
CREATE TABLE PLAYER_STATS
	( GamerXUID		CHAR(16)		NOT NULL,
	  PlaylistID 		CHAR(2)			NOT NULL,
	  SeasonID 		CHAR(1)			NOT NULL,
	  TotalGames		INT,
	  Wins			INT,
	  Loses			INT,
	  Rank			CHAR(1),
	  Tier			INT,
	 PRIMARY KEY (GamerXUID, PlaylistID, SeasonID),
	 FOREIGN KEY (GamerXUID) REFERENCES PLAYERS(XUID), 
	 FOREIGN KEY (PlaylistID) REFERENCES PLAYLISTS(PID),
	 FOREIGN KEY (SeasonID) REFERENCES SEASONS(SID), 
	 FOREIGN KEY (Rank) REFERENCES RANKS(RankID) );
